import './globals.css';
import { Archivo } from 'next/font/google';
import i18nConfig from '../../../i18nConfig';
import { dir } from 'i18next';
import Head from 'next/head';

const archivo = Archivo({ subsets: ['latin'] });

export const metadata = {
  title: 'Sempen',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={archivo.className}>
        {children}
      </body>
    </html>
  );
}
